<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NDDC_Website_2024</RootNamespace>
    <UserSecretsId>cff96924-e293-4e0f-98fb-b0060b5c5262</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.36">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EFCore-Lib\EFCore-Lib.csproj" />
    <ProjectReference Include="..\NddcWebsiteLibrary\NddcWebsiteLibrary.csproj" />
  </ItemGroup>

</Project>
